source :rubygems

gem "rake-pipeline", :git => "git://github.com/livingsocial/rake-pipeline.git"
gem "rake-pipeline-web-filters", :git => "git://github.com/wycats/rake-pipeline-web-filters.git"
gem "tilt"
gem "haml"
gem "compass"
gem "json"
